#!/bin/bash

# =============================================================================
# COMPLETE SETUP AND RUN GUIDE - WiFi CSI Presence Detection
# =============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  WiFi CSI Presence Detection - Complete Setup Guide           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Store project root
PROJECT_ROOT="/Users/mizhabas/wifi_csi_imaging"

echo "📍 Project Location: $PROJECT_ROOT"
echo ""

# =============================================================================
# STEP 1: Setup Python Environment
# =============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Setup Python Environment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command:"
echo "  cd $PROJECT_ROOT"
echo "  ./setup.sh"
echo ""
echo "This will:"
echo "  ✓ Create Python virtual environment"
echo "  ✓ Install numpy, scipy, matplotlib, pyserial"
echo "  ✓ Configure the project"
echo ""
read -p "Press Enter when done..."

# =============================================================================
# STEP 2: Configure WiFi Credentials
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Configure WiFi Credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Edit this file:"
echo "  $PROJECT_ROOT/firmware/csi_receiver/main/csi_receiver.c"
echo ""
echo "Change these lines (around line 14-15):"
echo '  #define WIFI_SSID "Connecting..."     ← Change to your WiFi name'
echo '  #define WIFI_PASS "Error501"          ← Change to your WiFi password'
echo ""
echo "⚠️  Important: ESP32 only works with 2.4GHz WiFi (not 5GHz)"
echo ""
read -p "Press Enter when done..."

# =============================================================================
# STEP 3: Build and Flash ESP32 Firmware
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Build and Flash ESP32 Firmware"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "  # Activate ESP-IDF"
echo "  source /Users/mizhabas/esp/esp-idf/export.sh"
echo ""
echo "  # Navigate to firmware directory"
echo "  cd $PROJECT_ROOT/firmware/csi_receiver"
echo ""
echo "  # Build firmware"
echo "  idf.py build"
echo ""
echo "  # Flash to ESP32 (replace /dev/cu.usbserial-* with your port)"
echo "  idf.py -p /dev/cu.usbserial-* flash"
echo ""
echo "  # Monitor output (optional - to verify it works)"
echo "  idf.py -p /dev/cu.usbserial-* monitor"
echo ""
echo "To find your ESP32 port, run: ls /dev/cu.*"
echo ""
echo "Expected output after flashing:"
echo "  ✓ WiFi Connected!"
echo "  ✓ CSI system active - presence detection ready"
echo "  CSI_DATA: 23 45 67 89 12 34 56 78..."
echo ""
read -p "Press Enter when done..."

# =============================================================================
# STEP 4: Run Presence Detection
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Run Presence Detection System"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "  # Navigate to python directory"
echo "  cd $PROJECT_ROOT/python"
echo ""
echo "  # Activate virtual environment"
echo "  source env/bin/activate"
echo ""
echo "  # Run the detector (auto-detects ESP32)"
echo "  python3 run_presence_detection.py"
echo ""
echo "  # OR specify port manually"
echo "  # python3 run_presence_detection.py /dev/cu.usbserial-*"
echo ""
echo "  # OR run simple mode"
echo "  # python3 run_presence_detection.py simple"
echo ""
echo "What happens next:"
echo "  1. System finds your ESP32 automatically"
echo "  2. Connects and receives CSI data"
echo "  3. Calibration phase (10 seconds - stay still!)"
echo "  4. Real-time presence detection with graphs"
echo ""
echo "Detection Status:"
echo "  🏠 EMPTY          - No person detected"
echo "  🧍 PERSON_STILL    - Person present, not moving"
echo "  🚶 PERSON_MOVING   - Person walking/active"
echo "  👥 HIGH_ACTIVITY   - Multiple people"
echo ""
read -p "Press Enter to see quick reference commands..."

# =============================================================================
# QUICK REFERENCE
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "QUICK REFERENCE - Copy These Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Setup (first time only):"
echo "cd $PROJECT_ROOT && ./setup.sh"
echo ""
echo "# Build ESP32 firmware:"
echo "source /Users/mizhabas/esp/esp-idf/export.sh"
echo "cd $PROJECT_ROOT/firmware/csi_receiver"
echo "idf.py build flash monitor"
echo ""
echo "# Run detection:"
echo "cd $PROJECT_ROOT/python"
echo "source env/bin/activate"
echo "python3 run_presence_detection.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Your code is ERROR-FREE and ready to use!"
echo ""
echo "📚 For detailed help, see:"
echo "   - README.md         (full documentation)"
echo "   - QUICKSTART.md     (5-minute guide)"
echo "   - TROUBLESHOOTING.md (problem solving)"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Ready to detect presence! Good luck! 🎯                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
