#!/bin/bash

# ============================================================================
# QUICK START - Complete Workflow
# ============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║      🚀 WiFi CSI PRESENCE DETECTION - QUICK START             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

PROJECT_ROOT="/Users/mizhabas/wifi_csi_imaging"

echo "📝 COMPLETE WORKFLOW:"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "PHASE 1: BUILD & FLASH ESP32 FIRMWARE"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Connect ESP32 to USB"
echo ""
echo "2️⃣  Run firmware builder:"
echo "   bash $PROJECT_ROOT/FLASH_ESP32.sh"
echo ""
echo "   This will:"
echo "   • Verify WiFi credentials (Connecting.../Error501)"
echo "   • Build ESP32 firmware"
echo "   • Flash to ESP32"
echo "   • Show serial output"
echo ""
echo "   ✅ Wait for: 'CSI system active - presence detection ready'"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "PHASE 2: RUN WEB SERVER (Real-time Detection)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "3️⃣  In a NEW terminal, start the web server:"
echo "   cd $PROJECT_ROOT/python"
echo "   source env/bin/activate"
echo "   python3 web_monitor_server.py"
echo ""
echo "   ✅ Wait for: 'Server running! Open http://localhost:8080'"
echo ""
echo "4️⃣  Open browser:"
echo "   http://localhost:8080"
echo ""
echo "5️⃣  Watch real-time detection:"
echo "   • Chart shows CSI energy values"
echo "   • Status shows: EMPTY ROOM / PERSON PRESENT / MULTIPLE PEOPLE"
echo "   • Variance graph with threshold lines"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "❌ WiFi not connecting?"
echo "   → Check SSID: 'Connecting...'"
echo "   → Check password: 'Error501'"
echo "   → Verify 2.4GHz WiFi (not 5GHz)"
echo "   → Check router firewall settings"
echo ""
echo "❌ No CSI data in web server?"
echo "   → Check ESP32 is powered and connected"
echo "   → Run: idf.py -p /dev/cu.usbserial-0001 monitor"
echo "   → Look for 'CSI_DATA:' output"
echo ""
echo "❌ Web server won't start?"
echo "   → Make sure web_monitor_server.py can find ESP32"
echo "   → Try: python3 web_monitor_server.py --port /dev/cu.usbserial-0001"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "TESTING WITH RECORDED DATA"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Test without ESP32 (using pre-recorded calibrated data):"
echo "   cd $PROJECT_ROOT/python"
echo "   source env/bin/activate"
echo "   python3 auto_calibrate.py"
echo ""
echo "This loads calibration.json with optimal thresholds:"
echo "   • Empty: < 4.64 variance"
echo "   • Person: 4.64 - 5.37 variance"
echo "   • Multiple: > 5.37 variance"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "RECALIBRATION (if accuracy issues)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "If detection isn't accurate enough:"
echo "   cd $PROJECT_ROOT/python"
echo "   source env/bin/activate"
echo "   python3 RECALIBRATE.py"
echo ""
echo "This re-calibrates by:"
echo "   1. Stopping old server"
echo "   2. Waiting 30 seconds (empty room baseline)"
echo "   3. Calculating new thresholds"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""

read -p "Ready to start? Run: bash $PROJECT_ROOT/FLASH_ESP32.sh"
